Updated to v10
thesadrogue/TheSadRogue.Integration pull request #76
Opened 2023-11-10 03:44 UTC by Chris3606

The purpose of this PR is to do a fairly minimal set of changes that update the integration library to SadConsole v10.

A few limitations:
- Only single cell entities are supported (this is due to `GameObject` limitations)
-

2023-11-10 05:02 UTC, Thraka requested changes
Few things to note and wait on the next update to SC

2023-11-11 16:03 UTC, Chris3606 commented on TheSadRogue.Integration/Maps/MapTerrainCellSurface.cs
> +        }
Removed

2023-11-11 16:03 UTC, Chris3606 commented on ExampleGame/Program.cs
>              GameHost.Instance.DestroyDefaultStartingConsole();
Removed

2023-11-22 16:20 UTC, Thraka commented
I just pushed an update to the branch. Also, the template is pointing to the local copy of the integration library. Since I didn't know what version you wanted to use, so you'll need to modify the project files with new versions and remove those local references.

Changes:

1. I updated the individual templates to match the default SadConsole template.
2. Changed a few comments where there were double spaces to single spaces.
3. Startup modernized and cleaned up.
4. MonoGame template has the app manifest file.
5. Because of implicit usings, removed SadConsole namespaces where appropriate.

2023-11-23 06:31 UTC, Thraka approved these changes

2024-01-08 14:11 UTC, merged